### ISSUE TITLE
Communication with Python script

### ISSUE THREAD

**Issue by iBobik** [balena-io-projects/balena-wpe#44]
I want to communicate with an RFID reader connected to Pi by GPIO. I am able to process that values by Python script.

How that Python script can send some event to SPA running in Webkit?

**Comment by iBobik** [comment]
Maybe turning WPE to multicontainer like in #29 and in second container run websocket server available only to other containers, so app in browser can access it over HTTP?

**Comment by petrosagg** [comment]
@iBobik yeah that's the general idea. Having wpe run as a separate container that gets all its data over HTTP by talking to other containers running next to it

**Comment by Controlhaus** [comment]
@iBobik Communicating between containers over a websocket works well.  
Here is what our docker-compose.yml looks like to do that:  

```yaml
version: '2.1'
services:
  my-app:
    build: ./my-app
    privileged: true
    restart: always
    depends_on:
      - display
    network_mode: host
  display:
    build: ./wpe
    devices:
      - "/dev/fb0:/dev/fb0"
      - "/dev/vchiq:/dev/vchiq" 
    restart: always
    network_mode: host
```
